# dictionary of stock names and symbols

stock_names_symbols = {
    "Adani Ports and Special Economic Zone": "ADANIPORTS",
    "Asian Paints": "ASIANPAINT",
    "Axis Bank": "AXISBANK",
    "Bajaj Auto": "BAJAJ-AUTO",
    "Bajaj Finserv": "BAJAJFINSV",
    "Bajaj Finance": "BAJFINANCE",
    "Bharti Airtel": "BHARTIARTL",
    "BPCL": "BPCL",
    "Britannia Industries": "BRITANNIA",
    "Cipla": "CIPLA",
    "Coal India": "COALINDIA",
    "Dr. Reddy's Laboratories": "DRREDDY",
    "Eicher Motors": "EICHERMOT",
    "GAIL": "GAIL",
    "Grasim Industries": "GRASIM",
    "HCL Technologies": "HCLTECH",
    "HDFC": "HDFC",
    "HDFC Bank": "HDFCBANK",
    "Hero MotoCorp": "HEROMOTOCO",
    "Hindalco Industries": "HINDALCO",
    "Hindustan Unilever": "HINDUNILVR",
    "ICICI Bank": "ICICIBANK",
    "IndusInd Bank": "INDUSINDBK",
    "Infosys": "INFY",
    "Indian Oil Corporation": "IOC",
    "ITC": "ITC",
    "JSW Steel": "JSWSTEEL",
    "Kotak Mahindra Bank": "KOTAKBANK",
    "Larsen & Toubro": "LT",
    "Maruti Suzuki India": "MARUTI",
    "Mahindra & Mahindra": "MM",
    "Nestle India": "NESTLEIND",
    "NTPC": "NTPC",
    "Oil & Natural Gas Corporation": "ONGC",
    "Power Grid Corporation of India": "POWERGRID",
    "Reliance Industries": "RELIANCE",
    "Shree Cement": "SHREECEM",
    "Sun Pharmaceutical Industries": "SUNPHARMA",
    "Tata Motors": "TATAMOTORS",
    "Tata Steel": "TATASTEEL",
    "Tata Consultancy Services": "TCS",
    "Tech Mahindra": "TECHM",
    "Titan Company": "TITAN",
    "UltraTech Cement": "ULTRACEMCO",
    "UPL": "UPL",
    "Vedanta": "VEDL",
    "Wipro": "WIPRO",
}

# stock_names_symbols = {
#     "ACC": "ACC",
#     "Adani Green Energy": "ADANIGREEN",
#     "Adani Ports and Special Economic Zone": "ADANIPORTS",
#     "Ambuja Cements": "AMBUJACEM",
#     "Apollo Hospitals Enterprise": "APOLLOHOSP",
#     "Adani Enterprises": "ADANIENT",
#     "Asian Paints": "ASIANPAINT",
#     "Aurobindo Pharma": "AUROPHARMA",
#     "Axis Bank": "AXISBANK",
#     "Bajaj Auto": "BAJAJ-AUTO",
#     "Bajaj Finserv": "BAJAJFINSV",
#     "Bajaj Holdings & Investment": "BAJAJHLDNG",
#     "Bajaj Finance": "BAJFINANCE",
#     "Bandhan Bank": "BANDHANBNK",
#     "Bank of Baroda": "BANKBARODA",
#     "Berger Paints": "BERGEPAINT",
#     "Bharti Airtel": "BHARTIARTL",
#     "Biocon": "BIOCON",
#     "Bosch": "BOSCHLTD",
#     "BPCL": "BPCL",
#     "Britannia Industries": "BRITANNIA",
#     "Cadila Healthcare": "CADILAHC",
#     "Cholamandalam Investment & Finance": "CHOLAFIN",
#     "Cipla": "CIPLA",
#     "Coal India": "COALINDIA",
#     "Colgate-Palmolive": "COLPAL",
#     "Dabur": "DABUR",
#     "Divi's Laboratories": "DIVISLAB",
#     "DLF": "DLF",
#     "Avenue Supermarts": "DMART",
#     "Dr. Reddy's Laboratories": "DRREDDY",
#     "Eicher Motors": "EICHERMOT",
#     "GAIL": "GAIL",
#     "Gland Pharma": "GLAND",
#     "Godrej Consumer Products": "GODREJCP",
#     "Grasim Industries": "GRASIM",
#     "Havells India": "HAVELLS",
#     "HCL Technologies": "HCLTECH",
#     "HDFC": "HDFC",
#     "HDFC AMC": "HDFCAMC",
#     "HDFC Bank": "HDFCBANK",
#     "HDFC Life Insurance Company": "HDFCLIFE",
#     "Hero MotoCorp": "HEROMOTOCO",
#     "Hindalco Industries": "HINDALCO",
#     "Hindustan Petroleum Corporation": "HINDPETRO",
#     "Hindustan Unilever": "HINDUNILVR",
#     "ICICI Bank": "ICICIBANK",
#     "ICICI Lombard General Insurance": "ICICIGI",
#     "ICICI Prudential Life Insurance": "ICICIPRULI",
#     "Indraprastha Gas": "IGL",
#     "IndiGo": "INDIGO",
#     "IndusInd Bank": "INDUSINDBK",
#     "Indus Towers": "INDUSTOWER",
#     "Infosys": "INFY",
#     "Indian Oil Corporation": "IOC",
#     "ITC": "ITC",
#     "Jindal Steel & Power": "JINDALSTEL",
#     "JSW Steel": "JSWSTEEL",
#     "Jubilant FoodWorks": "JUBLFOOD",
#     "Kotak Mahindra Bank": "KOTAKBANK",
#     "Larsen & Toubro": "LT",
#     "L&T Infotech": "LTI",
#     "Lupin": "LUPIN",
#     "Marico": "MARICO",
#     "Maruti Suzuki India": "MARUTI",
#     "United Spirits": "MCDOWELL-N",
#     "Muthoot Finance": "MUTHOOTFIN",
#     "Mahindra & Mahindra": "M_M",
#     "Info Edge (India)": "NAUKRI",
#     "Nestle India": "NESTLEIND",
#     "NMDC": "NMDC",
#     "NTPC": "NTPC",
#     "Oil & Natural Gas Corporation": "ONGC",
#     "Piramal Enterprises": "PEL",
#     "Procter & Gamble Hygiene and Health Care": "PGHH",
#     "Pidilite Industries": "PIDILITIND",
#     "PI Industries": "PIIND",
#     "Punjab National Bank": "PNB",
#     "Power Grid Corporation of India": "POWERGRID",
#     "Reliance Industries": "RELIANCE",
#     "Steel Authority of India": "SAIL",
#     "SBI Cards & Payment Services": "SBICARD",
#     "SBI Life Insurance Company": "SBILIFE",
#     "State Bank of India": "SBIN",
#     "Shree Cement": "SHREECEM",
#     "Siemens": "SIEMENS",
#     "Sun Pharmaceutical Industries": "SUNPHARMA",
#     "Tata Consumer Products": "TATACONSUM",
#     "Tata Motors": "TATAMOTORS",
#     "Tata Steel": "TATASTEEL",
#     "Tata Consultancy Services": "TCS",
#     "Tech Mahindra": "TECHM",
#     "Titan Company": "TITAN",
#     "Torrent Pharmaceuticals": "TORNTPHARM",
#     "UltraTech Cement": "ULTRACEMCO",
#     "UPL": "UPL",
#     "Vedanta": "VEDL",
#     "Wipro": "WIPRO",
#     "Yes Bank": "YESBANK"
# }